package C4::AgrovocWSService;
# Generated by SOAP::Lite (v0.710.10) for Perl -- soaplite.com
# Copyright (C) 2000-2006 Paul Kulchenko, Byrne Reese
# -- generated at [Mon Mar  1 12:42:15 2010]
# -- generated from file:./agrovoc_ws.wsdl
my %methods = (
getConceptInfoByTermcode => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcodestring', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptInfoByTermcode
searchCategoryByMode => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'schemeid', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchmode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'separator', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end searchCategoryByMode
searchCategoryByModeXML => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchmode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'schemeid', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end searchCategoryByModeXML
getTermByLanguageXML => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcode', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'language', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermByLanguageXML
getTermcodeByTerm => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'searchTerm', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermcodeByTerm
searchByTerm2 => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'separator', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end searchByTerm2
simpleSearchByModeXML => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchmode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end simpleSearchByModeXML
getAllLabelsByTermcode2 => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcode', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'separator', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getAllLabelsByTermcode2
getTermByLanguage => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcode', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'language', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermByLanguage
getTermsListByLanguageXML => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcodes_list', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'language', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermsListByLanguageXML
getTermsListByLanguage => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcodes_list', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'language', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermsListByLanguage
getConceptInfoByTermcodeXML => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcodestring', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptInfoByTermcodeXML
getAgrovocLanguages => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
    ], # end parameters
  }, # end getAgrovocLanguages
getDefinitions => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcode', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'languagecode', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getDefinitions
getTermsListByLanguage2 => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcodes_list', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'language', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'separator', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermsListByLanguage2
getAllLabelsByTermcode => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcode', type => 'xsd:int', attr => {}),
    ], # end parameters
  }, # end getAllLabelsByTermcode
getAllLabelsByTermcodeXML => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcode', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getAllLabelsByTermcodeXML
simpleSearchByMode => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchmode', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end simpleSearchByMode
simpleSearchByMode2 => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchmode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'separator', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end simpleSearchByMode2
getConceptByTerm => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'searchTerm', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptByTerm
searchByTerm => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end searchByTerm
getTermExpansion => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'query', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'langCode', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermExpansion
getDefinitionsXML => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'termcode', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'languagecode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getDefinitionsXML
searchByTermXML => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end searchByTermXML
getTermcodeByTermXML => {
    endpoint => 'http://www.fao.org/webservices/AgrovocWS',
    soapaction => '',
    namespace => 'http://www.fao.org/webservices/AgrovocWS',
    parameters => [
      SOAP::Data->new(name => 'searchTerm', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermcodeByTermXML
); # end my %methods

use SOAP::Lite;
use Exporter;
use Carp ();

use vars qw(@ISA $AUTOLOAD @EXPORT_OK %EXPORT_TAGS);
@ISA = qw(Exporter SOAP::Lite);
@EXPORT_OK = (keys %methods);
%EXPORT_TAGS = ('all' => [@EXPORT_OK]);

sub _call {
    my ($self, $method) = (shift, shift);
    my $name = UNIVERSAL::isa($method => 'SOAP::Data') ? $method->name : $method;
    my %method = %{$methods{$name}};
    $self->proxy($method{endpoint} || Carp::croak "No server address (proxy) specified")
        unless $self->proxy;
    my @templates = @{$method{parameters}};
    my @parameters = ();
    foreach my $param (@_) {
        if (@templates) {
            my $template = shift @templates;
            my ($prefix,$typename) = SOAP::Utils::splitqname($template->type);
            my $method = 'as_'.$typename;
            # TODO - if can('as_'.$typename) {...}
            my $result = $self->serializer->$method($param, $template->name, $template->type, $template->attr);
            push(@parameters, $template->value($result->[2]));
        }
        else {
            push(@parameters, $param);
        }
    }
    $self->endpoint($method{endpoint})
       ->ns($method{namespace})
       ->on_action(sub{qq!"$method{soapaction}"!});
  $self->serializer->register_ns("http://schemas.xmlsoap.org/wsdl/soap/","wsdlsoap");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/wsdl/","wsdl");
  $self->serializer->register_ns("http://www.fao.org/webservices/AgrovocWS","intf");
  $self->serializer->register_ns("http://www.fao.org/webservices/AgrovocWS","impl");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/soap/encoding/","soapenc");
  $self->serializer->register_ns("http://xml.apache.org/xml-soap","apachesoap");
  $self->serializer->register_ns("http://www.w3.org/2001/XMLSchema","xsd");
    my $som = $self->SUPER::call($method => @parameters);
    if ($self->want_som) {
        return $som;
    }
    UNIVERSAL::isa($som => 'SOAP::SOM') ? wantarray ? $som->paramsall : $som->result : $som;
}

sub BEGIN {
    no strict 'refs';
    for my $method (qw(want_som)) {
        my $field = '_' . $method;
        *$method = sub {
            my $self = shift->new;
            @_ ? ($self->{$field} = shift, return $self) : return $self->{$field};
        }
    }
}
no strict 'refs';
for my $method (@EXPORT_OK) {
    my %method = %{$methods{$method}};
    *$method = sub {
        my $self = UNIVERSAL::isa($_[0] => __PACKAGE__)
            ? ref $_[0]
                ? shift # OBJECT
                # CLASS, either get self or create new and assign to self
                : (shift->self || __PACKAGE__->self(__PACKAGE__->new))
            # function call, either get self or create new and assign to self
            : (__PACKAGE__->self || __PACKAGE__->self(__PACKAGE__->new));
        $self->_call($method, @_);
    }
}

sub AUTOLOAD {
    my $method = substr($AUTOLOAD, rindex($AUTOLOAD, '::') + 2);
    return if $method eq 'DESTROY' || $method eq 'want_som';
    die "Unrecognized method '$method'. List of available method(s): @EXPORT_OK\n";
}

1;
